### ISSUE TITLE
wearing armor items doubled in chest when jail player

### ISSUE THREAD

**Issue by BabelSolea** [graywolf336/Jail#146] opened 2017-01-23 15:50 UTC
Jail ver: 2.6.5-b3 (other versions not working on 1.11.2)
Spigot 1.11.2

When jail any player
her items in head/body/pants/boots slots creating twice in cell chest.

if not use cells anyway unjail player - give him that items twice.

can ure pls fix that? or may be release version to spigot 1.11.2 ?

**Comment by graywolf336** [comment] 2017-01-23 16:21
Duplicate of #118. Use one of the developer builds: https://ci.craftyn.com/job/Jail/

**Closed by graywolf336** 2017-01-23 16:21 UTC
