### ISSUE TITLE
Jailcreate Double Click 1.10.2 [BUG]

### ISSUE THREAD

**Issue by ericksantos12** [graywolf336/Jail#132] opened 2016-11-02 01:15 UTC
Jail plugin dont works from 1.10 users because when right click for select region and select both (First and Second Point) like double click, **PLEASE FIX THIS** i really want to play with my friends with this mod

**Comment by graywolf336** [comment] 2016-11-02 02:07
Duplicate of #114

**Closed by graywolf336** 2016-11-02 02:07 UTC
