### ISSUE TITLE
Multiworld inventory issue

### ISSUE THREAD

**Issue by JohOply** [graywolf336/Jail#103] opened 2015-12-23 18:04 UTC
Hi,

I have a lot of worlds on my server, with differents inventories. i have a jail in one world only (world A for instance). If a player is jailed when he is in another world (world B for instance) with a different inventory, plugin will store inventory from the B world and the player will loose the inventory from the A world.

If you don't understand something, please tell me, french isn't my native language :)

Thanks in advance to fix it

**Comment by graywolf336** [comment] 2015-12-23 18:27
Duplicate of #100.

**Closed by graywolf336** 2015-12-23 18:27 UTC
