### ISSUE TITLE
region selection not working

### ISSUE THREAD

**Issue by miketorman** [graywolf336/Jail#96] opened 2015-10-21 22:06 UTC
When trying to set up a jail's region the selection system is not registering where I'm selecting. I tried to enter debug mode to see what was wrong but it just gives me the error that there are no jails. It would probably be easier to hook the selection system into world edit instead of trying to do a standalone yourself.

**Comment by graywolf336** [comment] 2015-10-22 01:21
Duplicate of #95, but I think I know the issue and will be changing it this week or next.

**Closed by graywolf336** 2015-10-22 01:21 UTC
