### ISSUE TITLE
Problem in jail/cell creation

### ISSUE THREAD

**Issue by FiranWolf** [graywolf336/Jail#122] opened 2016-04-23 23:18 UTC
Whenever I try to create a jail, or a jail cell, the sword which is given to select the regions will always select twice. For example, it says to select a point at the bottom right of the jail, I select it... But it has also selected the same point as being the one which is supposed to be at the top left.

Here's a really short video which shows the issue a little better: https://drive.google.com/file/d/0B7Ev4MrLNk1RNC1FOTB0eE54U2M/view?usp=sharing

Since it doesn't select boundaries and other settings properly, I have to proceed like in the video and after that I need to edit the data.yml and restart the server if I want a nicely set jail.
I'm running a Spigot 1.9 server, if that could be causing it!

**Comment by graywolf336** [comment] 2016-04-23 23:25
Duplicate of #114

**Closed by graywolf336** 2016-04-23 23:25 UTC

**Comment by FiranWolf** [comment] 2016-04-23 23:28
@graywolf336 
Oh, sorry, I hadn't seen that issue.
Thanks for referencing me to it!

**Comment by graywolf336** [comment] 2016-04-23 23:30
No problem, please use the latest build though and let me know how everything works for you. As I need people to test it and verify nothing else is wrong with 1.9 so I can upload to Bukkit Dev

**Comment by FiranWolf** [comment] 2016-04-23 23:34
Alright!
Just to make sure, the latest build is #264 right?

**Comment by graywolf336** [comment] 2016-04-23 23:37
Whichever is the latest on the Jenkins, I don't remember which number was the latest

**Comment by FiranWolf** [comment] 2016-04-23 23:40
Okay, so if I encounter an other issue I'll just post a new ticket!

**Comment by graywolf336** [comment] 2016-04-23 23:42
Thanks!
