### ISSUE TITLE
Protections how and where to edit ?

### ISSUE THREAD

**Issue by BroCrafter14** [graywolf336/Jail#84] opened 2015-07-10 12:36 UTC
Hello, 
I have downloaded the plugin a while back now, but what I ma wondering is how and where to find and change these protection settings mentioned here : http://dev.bukkit.org/bukkit-plugins/jail/pages/protections/ I tryed everything I could think of (Adding line to config, trying unlisted commands, making different file called Protections.yml) but nothing works. I would like my players to have guards spawn around them when they exit the jail and if they kll them they are free.

Please help,
SRJ

**Comment by graywolf336** [comment] 2015-07-10 14:39
Duplicate of #13. Guards are currently unimplemented in beta version 3, as it has been requested another time I will make this up there on the list for implementing next.

**Closed by graywolf336** 2015-07-10 14:39 UTC
