### ISSUE TITLE
Bug during creation of jail 

### ISSUE THREAD

**Issue by Diissolution** [graywolf336/Jail#115] opened 2016-03-22 19:29 UTC
Hi
I'm gonna try to do my best in my written english because i'm french ^^
When i want to create my jail with /jailcreate, it give me the sword, broadcast me to right click to select the region OK. 
But when i do the first right click, it automatically set the second point at the same time.
I was thinking that my mouse was the problem, but friends had the same problem.

I hope that you will understand my bug :D

I'm on Spigot Bungee 1.9, seems that bukkit users have this bug too.

Thank you.

**Comment by graywolf336** [comment] 2016-03-22 19:30
Duplicate of #114. Please search for issues, closed and open, before opening a new one. Thanks.

**Closed by graywolf336** 2016-03-22 19:30 UTC

**Comment by Diissolution** [comment] 2016-03-22 19:37
I'm sorry i'm new using GitHub, i wasn't able to find other subjects
