### ISSUE TITLE
Big Error

### ISSUE THREAD

**Issue by legomasterev3** [graywolf336/Jail#129] opened 2016-07-11 15:58 UTC
when i type /jailcreate jail1 and give me the sword after clicking just one time in a block to set the pos 1 say tha i have select both pos 1 and 2 pls help me thanks for your time.

**Comment by graywolf336** [comment] 2016-07-11 16:17
What version are you on of everything?

**Comment by graywolf336** [comment] 2016-07-11 16:18
Actually, duplicate of #114.

**Closed by graywolf336** 2016-07-11 16:18 UTC
