### ISSUE TITLE
Signs Disappearing on Reloading of Jail

### ISSUE THREAD

**Issue by FutureMagick** [graywolf336/Jail#67] opened 2015-05-04 10:28 UTC
the signs up not showing up with players info times or reason 

  cellsign:
    - '%player%'
    - '%timeinminutes% mins'
    - with a reason
    - '%reason%'

is what we have in our settings

**Comment by Dragon12dk** [comment] 2015-05-06 23:55
Same thing is happening for me.

**Comment by graywolf336** [comment] 2015-05-07 01:28
Any errors in the logs?

**Comment by Dragon12dk** [comment] 2015-05-07 02:14
Not for me, Here is what I have in my config.
    cellsign:
    - '%player%'
    - '%timeinminutes% mins'
    - jailed by the
    - '%reason%'

**Comment by FutureMagick** [comment] 2015-05-07 02:47
Hi Graywolf

 

thank you for getting back to me

 

Just have to say one I love your plug in it goes so well with our server that is jail based 

 

We are on 1.7.10 but using your jail 3 

 

I have noted when you edit the config the signs stop working and you have to redo the cells

 

I have tried your 1.7.2 jail 2

 

And loved escaping  and the Guard that you have left out hope your bring back we set up mazes and all lol 

 

Did have a problem with the jail wand we couldn’t select anything but I reloaded the mod and that’s now working

 

Thanks again 

 

 

FutureMagick

OhGaming Manager

**Comment by graywolf336** [comment] 2015-05-07 17:36
Okay, I will have to look into this as this is a big problem..I need to see if they're updating on my server or not.

And the items that used to be enabled which aren't are planned, hoping I'll have time in the summer to implement them.

**Comment by graywolf336** [comment] 2015-05-10 07:05
Pretty easy to replicate: reload the plugin via `/jail reload` :disappointed: going to take a little bit to look into exactly why this happens. Are you guys using flatfile or mysql as the storage?

**Comment by FutureMagick** [comment] 2015-05-10 07:10
Flatfiles and did the jail reload 

All the best 

Chris

**Comment by graywolf336** [comment] 2015-05-10 07:12
Okay cool, I'm testing with flatfile as well but curious if anyone else is using MySQL and having this issue. I don't think on my main server where this is being used I've had the problem, but honestly not sure if I've did a jail reload on there...

**Comment by FutureMagick** [comment] 2015-05-10 21:54
Hi graywolf 

 

would it be possible to talk to via voice sometime I’m in TS ( ts.ohgaming.org ) name FutureMagick 

 

FutureMagick

**Comment by graywolf336** [comment] 2015-05-11 20:36
Depends on what you're wanting to discuss.

**Comment by hitechwizard** [comment] 2015-05-27 02:50
Confirmed this issue happens when using MySQL as the storage backend as well.

**Comment by FutureMagick** [comment] 2015-05-27 03:16
We use a flatfile not MySQL

**Comment by graywolf336** [comment] 2015-05-27 03:20
Yeah, I've been able to reproduce it with all storage systems. Was going to
track it down even further today but got busy with other items. Will try to
fix it tomorrow.

**Comment by graywolf336** [comment] 2015-05-27 16:37
Bad news...I wasn't able to reproduce the last several times using mysql as my storage system. :disappointed: Going to switch to flatfile and try duplicating it again that way.

**Comment by graywolf336** [comment] 2015-05-27 17:15
I will be closing this here shortly, **but** this changed no longer loads the *data* (jails, cells, prisoners) when the plugin is reloaded. Which means if you was used to editing the data.yml file then reloading that won't work anymore.

**Closed** 2015-05-27 17:26 UTC
Labels: bug

**Comment by graywolf336** [comment] 2015-05-27 17:34
Build 206 is under way and has the fix for this. You will need to recreate
the cells to add the signs back in, sorry.

**Comment by FutureMagick** [comment] 2015-05-28 01:18
That’s great news that you found it lol as for the cells Oh well lol

**Comment by FutureMagick** [comment] 2015-06-19 02:23
Hi hows the jail plug in going is it far from been fixed we are redoing the server and hoping to add yours to ours server again

 

FutureMagick

**Comment by graywolf336** [comment] 2015-06-19 03:24
Depends on what you need the plugin to do. I've been using it on my server for a while now. We don't use guards, so if you use that then no it isn't ready. Other than that, it is stable from what I can tell and now has some command tab completion enabled.

**Comment by FutureMagick** [comment] 2015-06-19 04:01
Was this where the signs didn’t work once you changed the configs

 

Someone sent this to me a month ago

 

On Tue, May 26, 2015 at 10:20 PM, Craftyn Towny Server <
graywolf336@craftyn.com <mailto:graywolf336@craftyn.com> > wrote:

> Yeah, I've been able to reproduce it with all storage systems. Was going
> to track it down even further today but got busy with other items. Will try
> to fix it tomorrow.



 

Build 206 is under way and has the fix for this. You will need to recreate
the cells to add the signs back in, sorry.

 

FutureMagick

**Comment by graywolf336** [comment] 2015-06-19 04:16
As the issue is closed, it has been resolved.

**Comment by FutureMagick** [comment] 2015-06-19 04:33
Sorry bit confused because never added anything to the plugin to stop this

Are you saying it is fix and signs work

all the time??

**Comment by graywolf336** [comment] 2015-06-19 04:56
Yes. It was fixed with https://github.com/graywolf336/Jail/commit/55062bc03aff659770f4bed83b3cc359b634688a and if you have problems with signs, please open a new issue.

**Comment by FutureMagick** [comment] 2015-06-19 05:37
Sorry that makes no sence in what I’m to do with that

**Comment by graywolf336** [comment] 2015-06-19 13:47
The issue of which you're commenting on has been fixed. If you have any problems with the most recent builds, please open a new issue.
