### ISSUE TITLE
Jail + Multiworlds

### ISSUE THREAD

**Issue by Fido2603** [graywolf336/Jail#101] opened 2015-11-13 15:51 UTC
I have a problem on a server where we have a creative world and a survival world. The jail is in the survival world but when we jail someone that is in the creative world they get teleported to the survival world with their creative inventory. So when they get releashed they get their creative inventory into the survival world. We use Jail 3.0 i think. Is there a fx to this?

**Comment by graywolf336** [comment] 2015-11-13 16:13
You can choose to release them back to their original position.

Closing as it's a duplicate of #100.

**Closed by graywolf336** 2015-11-13 16:13 UTC
